### ISSUE TITLE
How RWKV-v2-RNN is converted to onnx

### ISSUE THREAD

**Issue by ZTMIDGO** [AXKuhta/rwkv-onnx-dml#1]
I converted rwkv-4 to onnx based on your code, but I can't convert rwkv-v2-rnn to onnx

**Comment by AXKuhta** [comment]
This code was never intended for rwkv-v2-rnn. They have some architectural differences. But in general, [this](https://github.com/AXKuhta/RWKV-LM/commit/8f2874f4116e1b6891c76e7fa08a5fdbbc4e4e0e) and [this](https://github.com/AXKuhta/RWKV-LM/commit/669a7e967d2dc0a41d7bb80527714268b945d530) needs to be changed in the model code, at which point it can be exported to onnx [like here](https://github.com/AXKuhta/RWKV-LM/commit/a0f585ee98e44fa9888e7a4ba68b5f13136958d7).

Is there some reason in particular you want to export the old model?

**Comment by ZTMIDGO** [comment]
This project
https://github.com/AXKuhta/RWKV-LM
RWKV-v4 has a conversion code and can be converted successfully, but RWKV-v2-rnn can't use RWKV-v4's conversion code, can you tell me how to do it?

**Comment by AXKuhta** [comment]
@ZTMIDGO Add the changes that I mentioned above ([this](https://github.com/AXKuhta/RWKV-LM/commit/8f2874f4116e1b6891c76e7fa08a5fdbbc4e4e0e) and [this](https://github.com/AXKuhta/RWKV-LM/commit/669a7e967d2dc0a41d7bb80527714268b945d530)) to https://github.com/BlinkDL/RWKV-v2-RNN-Pile/blob/main/RWKV-v2/src/model.py but omit the pp_att/self.pp lines because RWKV-v2 doesn't have it.

Then the export_onnx.py script from [this commit](https://github.com/AXKuhta/RWKV-LM/commit/a0f585ee98e44fa9888e7a4ba68b5f13136958d7) should work but remove all uses of pp_att from it too.

**Comment by ZTMIDGO** [comment]
@AXKuhta Thank you very much, I'm trying to modify the code to convert the model, and if I get stuck, I hope you can guide me again

**Comment by ZTMIDGO** [comment]
Hello, I tried to convert 1B5 model to onnx with https://github.com/AXKuhta/RWKV-LM , the model address is https://huggingface.co/BlinkDL/rwkv-4-pile-1b5/blob/main/RWKV-4-Pile-1B5-EngChn-test4-20230115.pth here, but it prompts torch.onnx.CheckerError: The model does not have an ir_version set properly。 How do I fix it?
